year: 2018
channel: 0L
mc: true
luminosity: 59.7
signal-categories: ['$ZZ\ (Z \to ss)$']
sample-dir: /eos/user/l/legao/hss/samples/Tree/2018/0L/mc/pieces
merged-sample-dir: /eos/user/l/legao/hss/samples/BigTree/2018/0L/mc

hists:

  - name: HssVSQCD
    expr: '1.0 / (1.0 + (ak15_ParTMDV2_QCDbb + ak15_ParTMDV2_QCDb +
                         ak15_ParTMDV2_QCDcc + ak15_ParTMDV2_QCDc +
                         ak15_ParTMDV2_QCDothers) / ak15_ParTMDV2_Hss)'
    nbin: 50
    lb: 0.0
    ub: 1.0
    yscale: log
    grid: both
    stack: true
    no-stack-signal: true
    legend-options:
      ncol: 2
    subplot-significance-lower: true

  - name: HssVSQCD
    expr: '1.0 / (1.0 + (ak15_ParTMDV2_QCDbb + ak15_ParTMDV2_QCDb +
                         ak15_ParTMDV2_QCDcc + ak15_ParTMDV2_QCDc +
                         ak15_ParTMDV2_QCDothers) / ak15_ParTMDV2_Hss)'
    nbin: 50
    lb: 0.0
    ub: 1.0
    window: '[0.0, 1.0]'
    yscale: log
    grid: both
    legend-options:
      ncol: 2

  - name: kinBDT
    expr: kinBDT
    nbin: 50
    lb: 0.0
    ub: 1.0
    yscale: log
    grid: both
    stack: true
    no-stack-signal: true
    subplot-significance-lower: true

  - name: kinBDT
    expr: kinBDT
    nbin: 50
    lb: 0.0
    ub: 1.0
    window: '[0.0, 1.0]'
    grid: both
    stack: true

  - name: mass
    expr: 'ak15_sdmass'
    nbin: 50
    lb: 50.0
    ub: 300.0
    xlabel: 'Mass [GeV]'
    yscale: log
    grid: both
    stack: true
    no-stack-signal: true
    subplot-significance-lower: true
    subplot-significance-upper: true

  - name: mass
    expr: 'ak15_sdmass'
    nbin: 50
    lb: 50.0
    ub: 300.0
    window: '[0.0, inf]'
    xlabel: 'Mass [GeV]'
    grid: both
    stack: true

categories:

  - name: '$ZZ\ (Z \to dd/uu)$'
    samples:

      - name: SMP-RunIISummer20UL18MiniAODv2-00031-1
        dataset: ZZTo2Q2Nu_TuneCP5_13TeV-amcatnloFXFX-pythia8
        nevent: 453677
        xs-name: SMP-RunIIFall17MiniAODv2-00060-1  # [XXX] Fall17
        xs: 1.032

      - name: SMP-RunIISummer20UL18MiniAODv2-00031-2
        dataset: ZZTo2Q2Nu_TuneCP5_13TeV-amcatnloFXFX-pythia8
        nevent: 364688
        xs-name: SMP-RunIIFall17MiniAODv2-00060-2  # [XXX] Fall17
        xs: 0.728

  - name: '$ZZ\ (Z \to ss)$'
    samples:

      - name: SMP-RunIISummer20UL18MiniAODv2-00031-3
        dataset: ZZTo2Q2Nu_TuneCP5_13TeV-amcatnloFXFX-pythia8
        nevent: 417092
        xs-name: SMP-RunIIFall17MiniAODv2-00060-3  # [XXX] Fall17
        xs: 1.032

  - name: '$ZZ\ (Z \to cc)$'
    samples:

      - name: SMP-RunIISummer20UL18MiniAODv2-00031-4
        dataset: ZZTo2Q2Nu_TuneCP5_13TeV-amcatnloFXFX-pythia8
        nevent: 329918
        xs-name: SMP-RunIIFall17MiniAODv2-00060-4  # [XXX] Fall17
        xs: 0.784

  - name: '$ZZ\ (Z \to bb)$'
    samples:

      - name: SMP-RunIISummer20UL18MiniAODv2-00031-5
        dataset: ZZTo2Q2Nu_TuneCP5_13TeV-amcatnloFXFX-pythia8
        nevent: 442781
        xs-name: SMP-RunIIFall17MiniAODv2-00060-5  # [XXX] Fall17
        xs: 0.985

  - name: '$W + jets$'
    samples:

      - name: HIG-RunIISummer20UL18MiniAODv2-00220
        dataset: WJetsToLNu_Pt-100To250_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8
        nevent: 2030806
        xs-name: HIG-RunIISummer20UL17MiniAODv2-00059
        xs: 733.1

      - name: HIG-RunIISummer20UL18MiniAODv2-00218
        dataset: WJetsToLNu_Pt-250To400_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8
        nevent: 2013886
        xs-name: HIG-RunIISummer20UL17MiniAODv2-00048
        xs: 27.92

      - name: HIG-RunIISummer20UL18MiniAODv2-00219
        dataset: WJetsToLNu_Pt-400To600_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8
        nevent: 2016883
        xs-name: HIG-RunIISummer20UL17MiniAODv2-00049
        xs: 3.547

      - name: HIG-RunIISummer20UL18MiniAODv2-00009
        dataset: WJetsToLNu_Pt-600ToInf_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8
        nevent: 2007079
        xs-name: HIG-RunIISummer20UL17MiniAODv2-00047
        xs: 0.5371

  - name: '$Z + jets$'
    samples:

      - name: HIG-RunIISummer20UL18MiniAODv2-00917
        dataset: Z1JetsToNuNu_M-50_LHEFilterPtZ-50To150_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8
        nevent: 2033901
        xs-name: HIG-RunIISummer20UL17MiniAODv2-00809
        xs: 583.4

      - name: HIG-RunIISummer20UL18MiniAODv2-00918
        dataset: Z1JetsToNuNu_M-50_LHEFilterPtZ-150To250_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8
        nevent: 2077298
        xs-name: HIG-RunIISummer20UL17MiniAODv2-00810
        xs: 17.15

      - name: HIG-RunIISummer20UL18MiniAODv2-00919
        dataset: Z1JetsToNuNu_M-50_LHEFilterPtZ-250To400_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8
        nevent: 2013844
        xs-name: HIG-RunIISummer20UL17MiniAODv2-00811
        xs: 1.972

      - name: HIG-RunIISummer20UL18MiniAODv2-00920
        dataset: Z1JetsToNuNu_M-50_LHEFilterPtZ-400ToInf_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8
        nevent: 1620546
        xs-name: HIG-RunIISummer20UL17MiniAODv2-00812
        xs: 0.216

      - name: HIG-RunIISummer20UL18MiniAODv2-00921
        dataset: Z2JetsToNuNu_M-50_LHEFilterPtZ-50To150_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8
        nevent: 2064462
        xs-name: HIG-RunIISummer20UL17MiniAODv2-00813
        xs: 308.2

      - name: HIG-RunIISummer20UL18MiniAODv2-00922
        dataset: Z2JetsToNuNu_M-50_LHEFilterPtZ-150To250_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8
        nevent: 2053566
        xs-name: HIG-RunIISummer20UL17MiniAODv2-00814
        xs: 29.28

      - name: HIG-RunIISummer20UL18MiniAODv2-00923
        dataset: Z2JetsToNuNu_M-50_LHEFilterPtZ-250To400_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8
        nevent: 2001279
        xs-name: HIG-RunIISummer20UL17MiniAODv2-00815
        xs: 4.96

      - name: HIG-RunIISummer20UL18MiniAODv2-00924
        dataset: Z2JetsToNuNu_M-50_LHEFilterPtZ-400ToInf_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8
        nevent: 2004738
        xs-name: HIG-RunIISummer20UL17MiniAODv2-00816
        xs: 0.8318

  - name: '$VV\ (other)$'
    samples:

      - name: EXO-RunIISummer20UL18MiniAODv2-01344
        dataset: WWTo1L1Nu2Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8
        nevent: 2070890
        xs-name: EXO-RunIISummer20UL17MiniAODv2-01391
        xs: 51.65

      - name: SUS-RunIISummer20UL18MiniAODv2-00057
        dataset: WWTo2L2Nu_TuneCP5_13TeV-powheg-pythia8
        nevent: 2051000
        xs-name: SUS-RunIISummer20UL17MiniAODv2-00056
        xs: 11.09

      - name: SMP-RunIISummer20UL18MiniAODv2-00069
        dataset: WZTo3LNu_TuneCP5_13TeV-amcatnloFXFX-pythia8
        nevent: 9821283
        xs-name: SMP-RunIISummer20UL17MiniAODv2-00059
        xs: 5.257

      - name: EXO-RunIISummer20UL18MiniAODv2-01346-1
        dataset: WZTo1L1Nu2Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8
        nevent: 2078474
        xs-name: EXO-RunIISummer20UL17MiniAODv2-01393-1
        xs: 2.632

      - name: EXO-RunIISummer20UL18MiniAODv2-01346-2
        dataset: WZTo1L1Nu2Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8
        nevent: 1617824
        xs-name: EXO-RunIISummer20UL17MiniAODv2-01393-2
        xs: 1.856

      - name: EXO-RunIISummer20UL18MiniAODv2-01346-3
        dataset: WZTo1L1Nu2Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8
        nevent: 2078629
        xs-name: EXO-RunIISummer20UL17MiniAODv2-01393-3
        xs: 2.632

      - name: EXO-RunIISummer20UL18MiniAODv2-01346-4
        dataset: WZTo1L1Nu2Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8
        nevent: 1620560
        xs-name: EXO-RunIISummer20UL17MiniAODv2-01393-4

      - name: EXO-RunIISummer20UL18MiniAODv2-01347
        dataset: WZTo1L3Nu_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8
        nevent: 2013790
        xs-name: EXO-RunIISummer20UL17MiniAODv2-01394
        xs: 3.414

      - name: SMP-RunIISummer20UL18MiniAODv2-00054
        dataset: WZTo2Q2L_mllmin4p0_TuneCP5_13TeV-amcatnloFXFX-pythia8
        nevent: 2039277
        xs-name: SMP-RunIISummer20UL17MiniAODv2-00044
        xs: 6.565

#       - name:
#         dataset: (missing) <WZTo2L2Nu>
#         nevent:
#         xs-name:
#         xs:
#
      - name: SMP-RunIISummer20UL18MiniAODv2-00103
        dataset: ZZTo2Q2L_mllmin4p0_TuneCP5_13TeV-amcatnloFXFX-pythia8
        nevent: 2009005
        xs-name: SMP-RunIISummer20UL17MiniAODv2-00093
        xs: 3.676

      - name: HIG-RunIISummer20UL18MiniAODv2-00877
        dataset: ZZTo4L_TuneCP5_13TeV_powheg_pythia8
        nevent: 2077000
        xs-name: HIG-RunIIAutumn18MiniAOD-00016  # [XXX] Autumn18
        xs: 1.325

      - name: SUS-RunIISummer20UL18MiniAODv2-00053
        dataset: ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8
        nevent: 2087000
        xs-name: SUS-RunIISummer20UL17MiniAODv2-00036
        xs: 0.9738

  - name: '$tt$'
    samples:

      - name: TOP-RunIISummer20UL18MiniAODv2-00104
        dataset: TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8
        nevent: 2007000
        xs-name: PPD-RunIILowPUSummer20UL17MiniAODv2-00006
        xs: 687.1

      - name: TOP-RunIISummer20UL18MiniAODv2-00084
        dataset: TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8
        nevent: 2016000
        xs-name: TOP-RunIISummer20UL17MiniAODv2-00039
        xs: 687.1

  - name: '$Single$-$t$'
    samples:

      - name: TOP-RunIISummer20UL18MiniAODv2-00110
        dataset: ST_s-channel_4f_leptonDecays_TuneCP5_13TeV-amcatnlo-pythia8
        nevent: 2032000
        xs-name: TOP-RunIISummer20UL17MiniAODv2-00155
        xs: 3.549

      - name: TOP-RunIISummer20UL18MiniAODv2-00265
        dataset: ST_t-channel_antitop_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8
        nevent: 2018000
        xs-name: TOP-RunIISummer20UL17MiniAODv2-00247
        xs: 67.93

      - name: TOP-RunIISummer20UL18MiniAODv2-00264
        dataset: ST_t-channel_top_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8
        nevent: 2003000
        xs-name: TOP-RunIISummer20UL17MiniAODv2-00246
        xs: 113.4

      - name: TOP-RunIISummer20UL18MiniAODv2-00235
        dataset: ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8
        nevent: 2022000
        xs-name: TOP-RunIISummer20UL17MiniAODv2-00217
        xs: 32.51

      - name: TOP-RunIISummer20UL18MiniAODv2-00234
        dataset: ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8
        nevent: 2047000
        xs-name: TOP-RunIISummer20UL17MiniAODv2-00216
        xs: 32.45
